### PR TITLE
Validation on sector, form refactor, feedback messages on SectorController

### PR DESCRIPTION
**Pull request by efraimgentil**
1. Validation of uniqueness of Sector name
2. Secotr form refactor
3. Feedback messages on Sector CRUD
4. Exclusion of unused validation classes
5. Correction of some warning ( rawtipes, unused imports )

### CODE REVIEW

**Comment by htmfilho** [comment]
Sectors can have the same name under different departments or units or branches

**Comment by efraimgentil** [comment]
Yes, but it will have to be a diferent name, or how i will identify this
diferent sector in a diferent departments if all have the same name ?

2014-02-18 2:49 GMT-03:00 Hildeberto Mendonça notifications@github.com:

> Sectors can have the same name under different departments or units or
> branches
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cejug/hurraa/pull/98#issuecomment-35354872
> .

## 

Atenciosamente,
Efraim Gentil - @efraimgentil https://twitter.com/efraimgentil
Github https://github.com/efraimgentil
LinkedInhttp://www.linkedin.com/profile/view?id=215608595&trk=nav_responsive_tab_profile_pic

**Comment by htmfilho** [comment]
Hurraa cannot enforce that to the company. Some companies have a "finance" sector in several units. It's not the name of the sector that differentiates it, but its position in the company structure.

To be agile we have to deliver just the minimal to have it working and wait for users' feedback to improve and add constraints. By adding constraints at the beginning we might be forced to remove them in the future.

**Comment by efraimgentil** [comment]
I undestand that, but what will happen if tou have 2  sectors with the same
name in the system

"Finance" -> Madri
"Finance" -> Brasil

In the system how the user will see the diference if they have the same
name? the only indicator for this diference is the name, removing the
constrain is easier than adding, because adding you will have to resolve te
conflicted constrains, while removing you don't need o solve anithing.

2014-02-18 9:15 GMT-03:00 Hildeberto Mendonça notifications@github.com:

> Hurraa cannot enforce that to the company. Some companies have a "finance"
> sector in several units. It's not the name of the sector that
> differentiates it, but it position in the company structure.
> 
> To be agile we have to deliver just the minimal to have it working and
> wait for the user's feedback to improve and add constraints. By adding
> constraints at the beginning we might be forced to remove them in the
> future.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cejug/hurraa/pull/98#issuecomment-35378400
> .

## 

Atenciosamente,
Efraim Gentil - @efraimgentil https://twitter.com/efraimgentil
Github https://github.com/efraimgentil
LinkedInhttp://www.linkedin.com/profile/view?id=215608595&trk=nav_responsive_tab_profile_pic

**Comment by htmfilho** [comment]
If the unit is called Madri and Madri has a finance sector, we can show it to the user like "Madri/Finance", but just show, not name it like that because this sector can move to another unit (rengineering) and we wouldn't require the company to change its name unless it is really needed.

Today we have an entity "Sector" but it would be better to have "OrganizationUnit" instead with auto-relationship to enable the user to build the entire company structure. I'm not saying we should refactor it now. We can do it later.

In this case we could check for name duplicities only among units with the same parent.

**Comment by efraimgentil** [comment]
Yes that the point, but today we don't have the OrganizationUnit, like you
said the minimun viable is that we will have something usefull and not
confused, and then when we have the relationship we can take of the
constrains that will make no harm, and add the relationship.

I belive the unique constrains is viable now, so we don't need to worry
about confuse names, and then when whe create the OrganizationUnit we can
refactor and remove the constrains, that removing will make no hard work or
harm.

This is more like a belief than something that will make a real inpact on
the system, i just want to expose the reasons why i put the unique
constrains.

2014-02-18 9:42 GMT-03:00 Hildeberto Mendonça notifications@github.com:

> If the unit is called Madri and Madri has a finance sector, we can show it
> to the user like "Madri/Finance", but just show, not name it like that
> because this sector can move to another unit (rengineering) and we wouldn't
> require the company to change its name unless it is really needed.
> 
> Today we have an entity "Sector" but it would be better to have
> "OrganizationUnit" instead with auto-relationship to enable the user to
> build the entire company structure.
> 
> In this case we could check for name duplicities only among units with the
> same parent.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cejug/hurraa/pull/98#issuecomment-35380358
> .

## 

Atenciosamente,
Efraim Gentil - @efraimgentil https://twitter.com/efraimgentil
Github https://github.com/efraimgentil
LinkedInhttp://www.linkedin.com/profile/view?id=215608595&trk=nav_responsive_tab_profile_pic

**Comment by efraimgentil** [comment]
Removed the unique constrains on Secotr name.

**Pull request merged**
