### PR TITLE
Crud equipment validation

### PR DESCRIPTION
**Pull request by emanuelmm**
To complete the issue #46

### CODE REVIEW

**Comment by paulojribp** [comment]
Great @emanuelmm . @efraimgentil can you validate and merge if it's ok?

**Comment by efraimgentil** [comment]
Going to check it now

**Comment by efraimgentil** [comment]
Hi, @emanuelmm 

I have seen some problens in the request, some o then don't need to be corrected, like the date format for the date's field's  (#75 should handle that), and css for the form it can also be solved later.

But those listed bellow need to be solved so we can accept the pool:
1. The fields serialId, endOfWarranty and lastMaintenance have the constrains not null but are not validated as it
2. lastMaintenance field don't need to have not null constrains

Those are needed so we don't face exceptions while using the crud.

**Comment by emanuelmm** [comment]
Hi, @efraimgentil 
Ok... the first point will be resolved when we close issue #75... great!
I will close this PR and i will create other PR to resolve the others questions.
TY!

**Pull request closed without merging**
