### PR TITLE
better organization pom.xml arquillian stuff but still not working..

### PR DESCRIPTION
**Pull request by helio-frota**

### CODE REVIEW

**Comment by paulojribp** [comment]
@eprogramming Your file pom.xml is too much verbose because of WildFly specific configurations. We have already removed all configuration thats point to anyone specific Application Server.
I'm not sure if was you that add this, but it was there. Can you remove it?

**Comment by helio-frota** [comment]
@paulojribp Yes i added this.
The config to arquillian is big 
Please look: 
https://raw.github.com/javaee-samples/javaee7-samples/master/pom.xml

No problem about remove this. 
The main problem i think, is keep trying when more common unit tests can do the job too.

**Comment by paulojribp** [comment]
@eprogramming one more thing: if it's not working, it's better create a branch to merge this pull request. And who want to help with it, can pull the branch. What do you thing?

**Comment by helio-frota** [comment]
@paulojribp 
Going to delete the PR because now we need simple things

**Pull request closed without merging**
