### PR TITLE
Validation Sector with Bean Validation ( Using Hibernate Implementation  from JSR 303 )

### PR DESCRIPTION
**Pull request by efraimgentil**
Addition of errorMessage tag to simplify the use of the errors messages
Addition of singleCheckboxField tag  to simply the use of a imput type="checkbox" and with label 
Alteration of textField tag to handle errors too ( tested  and no colateral effects so far ) 
Addition of field "email", "respondsOccurrence" and "ative"  in Sector model
Addition of changelog in liquibase  to update the included fields in sector model  
Addition of ValidationUtil to handle bean validation

( Why not using @Valid, when using the annotation, the vraptor return a ${errors} list with the prefix of the action plus name of the attribute like 
  "insert.sector.name" = "some error message"
or when updating
  "update.sector.name" = "some error message"
i didn't found a workaround for this issue so i made my implementation to handle the error map )

### CODE REVIEW

**Comment by efraimgentil** [comment]
Sry i didn't know the others commit after the pull request will also be included in the pull =x

So lets explain arquillian configuration... you have two option to run the arquillian
1. Configure JBOSS_HOME enviroment variable pointing to your widfly directory
2. On arquillian.xml you configure the property jbossHome to point to your wildfly directory as there a commented example in the archive, like
<property name="jbossHome">/home/servidores/wildfly-8.0.0.CR1/</property>

**Comment by danielsoro** [comment]
Can I use embedded server (http://arquillian.org/modules/wildfly-arquillian-wildfly-embedded-container-adapter/)?

**Comment by efraimgentil** [comment]
I believe you can, actually i didn't know that there was a wildfly embedded
distribution, i going to check it out now =)

2014-01-30 Daniel Cunha notifications@github.com:

> Can I use embedded server (
> http://arquillian.org/modules/wildfly-arquillian-wildfly-embedded-container-adapter/)?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cejug/hurraa/pull/18#issuecomment-33683497
> .

## 

Atenciosamente,
Efraim Gentil - @efraimgentil https://twitter.com/efraimgentil
Github: efriamgentil https://github.com/efraimgentil

**Comment by danielsoro** [comment]
Great! We need your help. :-)

**Comment by paulojribp** [comment]
@efraimgentil Very good your solution, but why don't use the VRaptor validation? The ${erros} list all validation errors.
My point is only that this kind of thing the AS and Controller Frameworks should provide it to us.

**Comment by paulojribp** [comment]
In time, this is a very good commit. Thanks :)

**Comment by efraimgentil** [comment]
Actually i think bean validation is less verbose than vraptor validator,
less code involved and less complexity, thats a personal evaluation.
Later today i will make a different implementation for any other crud using
the vraptor validation and we make a comparison between then.

2014-01-30 Paulo A Junior notifications@github.com:

> In time, this is a very good commit. Thanks :)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cejug/hurraa/pull/18#issuecomment-33703631
> .

## 

Atenciosamente,
Efraim Gentil - @efraimgentil https://twitter.com/efraimgentil
Github: efriamgentil https://github.com/efraimgentil

**Comment by paulojribp** [comment]
Thats is ok @efraimgentil. We can update your implementations later to consider all message versions.

**Comment by danielsoro** [comment]
This is necessary:
 <dependency>
                        <groupId>org.hibernate</groupId>
                        <artifactId>hibernate-validator</artifactId>
                        <version>5.0.1.Final</version>
                </dependency>
??

When I added <dependency>
                        <groupId>javax</groupId>
                        <artifactId>javaee-web-api</artifactId>
                        <version>7.0</version>
                        <scope>provided</scope>
                </dependency>

I said that the server use your implementation then wildfly has this:
wildfly-8.0.0.CR1/modules/system/layers/base/org/hibernate/validator/main# ls
hibernate-validator-5.0.2.Final.jar  module.xml

I see that add the hibernate-validator in pom.xml isn't necessary.

Sorry with my english, I'm learning yet. :-)

**Comment by efraimgentil** [comment]
Actually it is necessary, without this dependency i get a exception that
say that i need a implementation of JSR 303, and that i have none in the
classpath.
I could use or HIbernate Validation or Apache Bean Validadtion( never used
just heard about ) or any other implementation of JSR 303, i prefered to use
 Hibernate Validation ( which don't have nothing to do with Hibernate ORM
except the name) couse i had already used in some projects.

javax
javaee-web-api
7.0
provided

Only will use the provided libs from the server that are explicit
declareden em javaee-web-api dependencies, and there only the JSR
especification and not the implementation, that i belive is a good way so
you can chose the implementation.

you can also mark hibernate-validator as provided so it will use the lib
from the wildfly but if you not explicit say it,  it will not find the lib

2014-01-30 Daniel Cunha notifications@github.com:

> This is necessary:
> 
> org.hibernate
> hibernate-validator
> 5.0.1.Final
> 
> ??
> 
> When I added
> javax
> javaee-web-api
> 7.0
> provided
> 
> I said that the server use your implementation then wildfly has this:
> wildfly-8.0.0.CR1/modules/system/layers/base/org/hibernate/validator/main#
> ls
> hibernate-validator-5.0.2.Final.jar module.xml
> 
> I see that add the hibernate-validator in pom.xml isn't necessary.
> 
> Sorry with my english, I'm learning yet. :-)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cejug/hurraa/pull/18#issuecomment-33706815
> .

## 

Atenciosamente,
Efraim Gentil - @efraimgentil https://twitter.com/efraimgentil
Github: efriamgentil https://github.com/efraimgentil

**Comment by danielsoro** [comment]
Good! :D

**Comment by helio-frota** [comment]
@danielsoro , @efraimgentil WILDFLY_HOME working
https://github.com/cejug/hurraa/commit/e3f4a393b157341e078424447f8912de12c1f66d

**Comment by danielsoro** [comment]
Great Helio! :)

**Pull request merged**
