### PR TITLE
#116 - Implementation of Problem Type CRUD

### PR DESCRIPTION
**Pull request by diogodias86**
#116 - Implementation of Problem Type CRUD

### CODE REVIEW

**Comment by efraimgentil** [comment]
Nive work @diogodias86

**Comment by paulojribp** [comment]
Greate work @diogodias86 welcome to Hurraa and to CEJUG

**Comment by danielsoro** [comment]
Uhuuuu! \o/

**Comment by helio-frota** [comment]
@diogodias86 welcome and well done !

**Comment by diogodias86** [comment]
hello guys, thanks!!! :) 
Very happy to contribute!!

**Pull request merged**
